package main

import "net"

// Returns a list of non-loopback IP addresses for the local device. These
// represent the source of traffic generated by this tool.
func GetLocalIPs() []string {
	var IPs []string
	addrs, err := net.InterfaceAddrs()
	if err == nil {
		for _, address := range addrs {
			// check the address type and if it is not a loopback the display it
			if ipnet, ok := address.(*net.IPNet); ok && !ipnet.IP.IsLoopback() {
				if ipnet.IP.To4() != nil {
					IPs = append(IPs, ipnet.IP.String())
				}
			}
		}
	}
	return IPs
}
