name: Build & Release

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  create:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Vet
      run: go vet

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -cover -v ./...

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        body_path: README.md
        files: connectivity
